### ISSUE TITLE
启动tick.py后小人不动，请问有解决办法吗

### ISSUE THREAD

**Issue by shirohasuki** [py499372727/AgentSims#2]
无报错，但是小人不动，不会对话交互，对话会报keyerror

**Comment by py499372727** [comment]
Hello, is the keyerror occurring at ['chat']['content']? If so, it is usually because the API_KEY is not configured correctly or the corresponding API is in arrears, which causes the GPT API to return a prompt that the balance is insufficient, thus failing to retrieve the correct response.
你好，keyerror的错误是发生在['chat']['content']吗？如果是的，通常是因为API_KEY没有配置正确或者相应的API欠费，导致GPT的API的返回值在提示余额不足，从而无法检索到正确的返回信息。

**Comment by shirohasuki** [comment]
感谢回复，确实是这个问题，更换key后keyerror的问题解决了。
但是小人还是不动，排查问题应该在每次对话后显示
1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
导致每次会返回的error，能接收我输入的，但是访问mysql可能有问题。感谢您的帮助。

**Comment by shirohasuki** [comment]
解决啦，感谢学长～我将mysql.py里面的连接设置强制改为我的密码（‘’）就连上了

**Comment by py499372727** [comment]
好的，也感谢您的关注，您的debug对于我们也意义重大
